services:
  app:
    build:
      context: .
      target: production
    image: billing-app:latest
    restart: unless-stopped
    ports:
      - '3050:3050'
    environment:
      NODE_ENV: production
      PORT: 3050
      DATABASE_URL: file:./prisma/dev.db
    volumes:
      - ./prisma:/app/prisma
