services:
  app:
    build:
      context: .
    image: helltv-payment:latest
    restart: unless-stopped
    ports:
      - '3050:3050'
    environment:
      NODE_ENV: production
      PORT: 3050
      DATABASE_URL: file:./prisma/dev.db
    volumes:
      # Database and initialization marker are persisted here
      - ./prisma:/app/prisma
